http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: '*'
    
  product:
    host: localhost
    paths: '/product/*'
  user:
    host: '*'
    paths: '/user/*'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  product:
    url: 'http://localhost:3001'
  user:
    url: 'http://localhost:3002'
  order:
    url: 'http://localhost:3003'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: user
              changeOrigin: true
  productsPipeline:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: product
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: user
              changeOrigin: true
  ordersPipeline:
    apiEndpoints:
      - order
    policies:
      - proxy:
          - action:
              serviceEndpoint: order
              changeOrigin: true