http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  product:
    host: localhost
    paths: '/products/*'
  user:
    host: localhost
    paths: '/users/*'
  orders:
    host: localhost
    paths: '/orders/*'

serviceEndpoints:
  productService:
    url: 'http://localhost:3001'
  userService:
    url: 'http://localhost:3002'
  orderService:
    url: 'http://localhost:3003'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  defaultPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  productsPipeline:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  ordersPipeline:
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
