http:
  port: 8080

https:
  port: 8443

admin:
  port: 9876
  host: localhost

apiEndpoints:
  product:
    host: localhost
    paths: '/product/*'
  user:
    host: localhost
    paths: '/user/*'
  orders:
    host: localhost
    paths: '/orders/*'

serviceEndpoints:
  product:
    url: 'https://localhost:3001'
  user:
    url: 'https://localhost:3002'
  order:
    url: 'https://localhost:3003'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  defaultPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: user
              changeOrigin: true
  productsPipeline:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: product
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: user
              changeOrigin: true
  ordersPipeline:
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action:
              serviceEndpoint: order
              changeOrigin: true
